---
# Look at the default configuration here
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
# extends: default

yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 80
    level: warning
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments
  comments:
    require-starting-space: true # this comment will failed
    ignore-shebangs: true # ignore shebangs when using require-starting-space
    min-spaces-from-content: 2  # Two spaces from the number 2
