groups:
- name: System alerts
  rules:
  - alert: NodeOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Node out of memory
      description: Node memory has reached {{ humanize $value}}%

- name: Containers
  rules:
  - alert: JenkinsHighMemory
    expr: sum(rate(container_cpu_usage_seconds_total{name="jenkins"}[5m]))*100 > 2
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: Jenkins high memory usage
      description: Jenkins memory consumption is at {{ humanize $value}}%